### ISSUE TITLE
Make tiny caps ignore color codes

### ISSUE THREAD

**Issue by koloja** [aabssmc/Skuishy#10]
make it so that when you do something like
`send "&ethis is yellow" in tiny caps` it wont ignore the `&e`
this actually lets you use color codes with this effect

**Comment by ghost** [comment]
you don't want color codes? or you do want color codes?

**Comment by koloja** [comment]
yes i would like them

**Comment by Fusezion** [comment]
I'm reopening this as I want a reminder for this, I'd like to see if I can implement it in the upcoming 2.8.1 release otherwise will 100% be in the 2.9.0 release

edit: on a side note it does appear he started work on a fix internally or he even might have completed it but a better system is likely possible so work will be done for it

**Comment by Fusezion** [comment]
This will be properly implemented in the 2.8.1 release 
![image](https://github.com/user-attachments/assets/f7288dde-5d04-4ddb-a6e7-ca7a2c508712)
